CREATE DATABASE Bao_cao1;

CREATE TABLE Cong_dung
(
  Ma_CD NVARCHAR(10) NOT NULL UNIQUE,
  Ten_CD NVARCHAR(100) NOT NULL,
  PRIMARY KEY (Ma_CD)
);

CREATE TABLE Doi_tuong_su_dung
(
  Ma_DT NVARCHAR(10) NOT NULL UNIQUE,
  Ten_DT NVARCHAR(100) NOT NULL,
  PRIMARY KEY (Ma_DT)
);

CREATE TABLE Thuong_hieu
(
  Ma_TH NVARCHAR(10) NOT NULL UNIQUE,
  Ten_TH NVARCHAR(100) NOT NULL,
  PRIMARY KEY (Ma_TH)
);

CREATE TABLE Loai_thuoc
(
  Ma_Loai NVARCHAR(10) NOT NULL UNIQUE,
  Ten_Loai NVARCHAR(100) NOT NULL,
  PRIMARY KEY (Ma_Loai)
);

CREATE TABLE Dang_bao_che
(
  Ma_BC NVARCHAR(10) NOT NULL UNIQUE,
  Ten_BC NVARCHAR(100) NOT NULL,
  PRIMARY KEY (Ma_BC)
);

CREATE TABLE Cach_dong_goi
(
  Ma_DG NVARCHAR(10) NOT NULL UNIQUE,
  Ten_DG NVARCHAR(50) NOT NULL,
  PRIMARY KEY (Ma_DG)
);

CREATE TABLE Khach_Hang
(
  Ma_KH NVARCHAR(10) NOT NULL UNIQUE,
  Ten_KH NVARCHAR(50) NOT NULL,
  SDT CHAR(10) NOT NULL,
  PRIMARY KEY (Ma_KH)
);

CREATE TABLE Hoa_Don
(
  So_HD NVARCHAR(10) NOT NULL UNIQUE,
  Ma_KH NVARCHAR(10) NOT NULL,
  Tong_Tien INT NOT NULL,
  Ngay_Ban DATE NOT NULL,
  PRIMARY KEY (So_HD),
  FOREIGN KEY (Ma_KH) REFERENCES Khach_Hang(Ma_KH)
);

CREATE TABLE Nhan_Vien
(
  Ma_NV NVARCHAR(10) NOT NULL UNIQUE,
  Ten_NV NVARCHAR(100) NOT NULL,
  SDT INT NOT NULL,
  Ngay_Sinh DATE NOT NULL,
  Gioi_Tinh CHAR(3) NOT NULL,
  Chuc_vu NVARCHAR(20) NOT NULL,
  PRIMARY KEY (Ma_NV)
);

CREATE TABLE Nha_Cung_Cap
(
  Ma_NCC NVARCHAR(10) NOT NULL UNIQUE,
  Ten_NCC NVARCHAR(100) NOT NULL,
  PRIMARY KEY (Ma_NCC)
);

CREATE TABLE Thuoc
(
  Ma_Thuoc NVARCHAR(10) NOT NULL UNIQUE,
  Ten_thuoc NVARCHAR(100) NOT NULL,
  Ma_Loai NVARCHAR(10) NOT NULL,
  Ma_CD NVARCHAR(10) NOT NULL,
  Ma_DT NVARCHAR(10) NOT NULL,
  Ma_TH NVARCHAR(10) NOT NULL,
  Noi_san_xuat NVARCHAR(50) NOT NULL,
  Ma_BC NVARCHAR(10) NOT NULL,
  Ma_DG NVARCHAR(10) NOT NULL,
  Ma_NCC NVARCHAR(10) NOT NULL,
  Han_su_dung NVARCHAR(50) NOT NULL,
  So_luong_con INT NOT NULL,	
  PRIMARY KEY (Ma_Thuoc),
  FOREIGN KEY (Ma_Loai) REFERENCES Loai_thuoc(Ma_Loai),
  FOREIGN KEY (Ma_TH) REFERENCES Thuong_hieu(Ma_TH),
  FOREIGN KEY (Ma_DT) REFERENCES Doi_tuong_su_dung(Ma_DT),
  FOREIGN KEY (Ma_CD) REFERENCES Cong_dung(Ma_CD),
  FOREIGN KEY (Ma_BC) REFERENCES Dang_bao_che(Ma_BC),
  FOREIGN KEY (Ma_DG) REFERENCES Cach_dong_goi(Ma_DG),
  FOREIGN KEY (Ma_NCC) REFERENCES Nha_Cung_Cap(Ma_NCC)
);

CREATE TABLE Chi_tiet_hoa_don
(
  So_HD NVARCHAR(10) NOT NULL,		
  Ma_Thuoc NVARCHAR(10) NOT NULL,
  So_Luong INT NOT NULL,
  PRIMARY KEY (Ma_Thuoc, So_HD),
  FOREIGN KEY (Ma_Thuoc) REFERENCES Thuoc(Ma_Thuoc),
  FOREIGN KEY (So_HD) REFERENCES Hoa_Don(So_HD)
);

CREATE TABLE Thanh_Toan_HD
(
  So_HD NVARCHAR(10) NOT NULL,
  Ma_NV NVARCHAR(10) NOT NULL,
  Tien_TT INT NOT NULL,
  Hinh_thuc_TT NVARCHAR(30) NOT NULL,
  Tien_thua INT NOT NULL,
  Ngay_thanh_toan DATE NOT NULL,
  PRIMARY KEY (So_HD, Ma_NV),
  FOREIGN KEY (So_HD) REFERENCES Hoa_Don(So_HD),
  FOREIGN KEY (Ma_NV) REFERENCES Nhan_Vien(Ma_NV)
);

CREATE TABLE Phieu_Nhap
(
  So_PN NVARCHAR(10) NOT NULL UNIQUE,
  Ma_NCC NVARCHAR(10) NOT NULL,
  Tong_Tien INT NOT NULL,
  Ngay_Nhap DATE NOT NULL, 
  PRIMARY KEY (So_PN),
  FOREIGN KEY (Ma_NCC) REFERENCES Nha_Cung_Cap(Ma_NCC)
);

CREATE TABLE Chi_tiet_phieu_nhap
(
  So_PN NVARCHAR(10) NOT NULL,
  Ma_Thuoc NVARCHAR(10) NOT NULL,
  So_luong INT NOT NULL,
  Don_gia INT NOT NULL, 
  PRIMARY KEY (So_PN, Ma_Thuoc),
  FOREIGN KEY (So_PN) REFERENCES Phieu_Nhap(So_PN),
  FOREIGN KEY (Ma_Thuoc) REFERENCES Thuoc(Ma_Thuoc)
);

CREATE TABLE Bien_dong_gia
(
  Ma_BD NVARCHAR(10) NOT NULL UNIQUE,
  Ma_Thuoc NVARCHAR(10) NOT NULL,
  Gia_BD INT NOT NULL,
  Ngay_BD DATE NOT NULL,
  PRIMARY KEY (Ma_BD),
  FOREIGN KEY (Ma_Thuoc) REFERENCES Thuoc(Ma_Thuoc)
);

CREATE TABLE Thanh_Toan_PN
(
  So_PN NVARCHAR(10) NOT NULL,
  Ma_NV NVARCHAR(10) NOT NULL,
  Ngay_TT DATE NOT NULL, 
  PRIMARY KEY (So_PN, Ma_NV),
  FOREIGN KEY (So_PN) REFERENCES Phieu_Nhap(So_PN),
  FOREIGN KEY (Ma_NV) REFERENCES Nhan_Vien(Ma_NV)
);
